### ISSUE TITLE
non-validated method for accessing files

### ISSUE THREAD

**Issue by danmarsden** [sam-19/moodle-filter_medimgviewer#2]
https://github.com/sam-19/moodle-filter_medimgviewer/blob/master/api.php#L41

It looks like you allow the user to pass any filearea and any filepath to your api.php file allowing a user to access files they should not be able to access, please validate that the user should be able to access the context/path being passed to your script.

note this is a blocker for approval.

**Comment by sam-19** [comment]
The documentation for this (that I could find) was not very extensive, so I used a method from your official plugins as an example and tried to implement it to the best of my knowledge. I'm not exactly sure how to test this as I couldn't adjust the access rights of individual files within a course area, but at least it didn't seem to break anything.

**Comment by danmarsden** [comment]
the fa and fp parameters allow the end-user to pass "anything" to the fields - eg here:
https://github.com/sam-19/moodle-filter_medimgviewer/blob/master/api.php#L48

The areaparts data is all from user submitted data passed via the end-user - you do not check does "this" user have access to view this context.

I can pass anything I want to $areaparts[0] - anything I want to $areaparts[1] and this can be a different context to the Coursemodule id passed in the "id" param into the script - allowing me to access files from contexts that are not inside the course I should have access to.

does that clarify?

**Comment by sam-19** [comment]
Yes, of course! Can't believe I missed that. This is not resolved then, I will have to get back to it later.

**Comment by sam-19** [comment]
Okay, @danmarsden, I think this should do it https://github.com/sam-19/moodle-filter_medimgviewer/commit/673e630ca38168d83c11564d68eab8cb8cabde4d. As a funny side-note, I was having a bit of a hard time with this one and even ended up asking ChatGPT for advice. It gave me a very convincing sounding explanation of a method called `can_access_filearea()`, but since I couldn't find any documentation on a method with that name, I decided to go with this approach instead.
